version: "3.3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    env_file:
      - ./.envs/.production/.django
    ports:
      - "15672:15672"
      - "15692:15692"
      - "5672:5672"
    networks:
      - proxy
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    # command: redis-server --requirepass redis_password
    ports:
      - "6379:6379"
      - "8002:8001"
    networks:
      - proxy
    restart: always
  nginxproxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginxproxy
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - static_mlb_v:/app_local/staticfiles
      - media_mlb_v:/app_local/mediafiles
    networks:
      - proxy
volumes:
  rabbitmq_data:
  static_mlb_v:
    external: true
  media_mlb_v:
    external: true

networks:
  proxy:
    external: true
